### ISSUE TITLE
VIM mode

### ISSUE THREAD

**Issue by let-def** [let-def/texpresso#11]
It would be nice to have a (neo)vim mode :).

It is probably quite easy on TeXpresso side (one would have to implement a parser for sexp-based TeXpresso protocol, that I should document!), but requires someone knowledgeable with (modern) vim internals.

**Comment by alerque** [comment]
Were you thinking or a *real* editor experience where a headless NeoVIM handles all the actual operations and a GUI widget compiled into TeXpresso acted as a UI with all the key inputs passed to the headless instance (for example this is how Firenvim provides a *real* editor experience in a browser text area) or where you thinking what most editors seem to mean by a VIM mode where they just emulate some of the modal bindings and map them to their own internal editor functions?

**Comment by let-def** [comment]
I was thinking of a plugin that shares the contents of vim buffers to a separate texpresso process.
You would have the editor, for instance, on the left side of the screen and the preview window on the right side.
It could be terminal vim, gvim, or any other modern frontend, as long as it is possible to use IPC to communicate between both processes.

From vim to texpresso, only the changes are shared, that can happen in realtime, and optionally the cursor position when I implement support for forward SyncTeX.
From texpresso to vim, it would share latex stdout and log files, and backward SyncTeX when the user click on the window.

**Comment by let-def** [comment]
I did not follow recent developments, but I am thinking of starting with NeoVIM and scripting with whatever is the preferred language there. I guess it is Lua, is it? I don't care much as long as it is portable across most platforms and builds of NeoVIM.

(In a previous life, I was a vim scripter, but I am no longer brave enough to deal with vimscript 🤷).

**Comment by alerque** [comment]
Yes Lua is the language to go with for new plugins targeting NeoVIM. It can handle Vimscript plugins (not the new Vimscript 9, just the legacy Vimscript) but you are limited in all the ways that language was a pain. Lua plugins are much faster, have much better support for async / multithreaded operations, and have access to lots of new APIs that legacy plugins can't even access. Lua has 100% access to legacy APIs but not the other way around. All NeoVIM builds across all supported platforms support Lua well now out of the box as it has been pushed hard upstream and many core routines have been ported to it making it a requirement not an optional build time feature like it used to be in the early days.

Later if a VIM version is desired at this point for an advanced plugin like this that does background messaging with an external process a Vimscript9 implementation might be desired for VIM folks.

For starting off the project, the only suggestion I'd make is not give it a NeoVIM specific name so that someday it could be expanded with a VIM9 implementation: so name it "texpresso.vim" instead of "texpresso.nvim" or whatever format you want to use (there isn't really a standard, "*.vim", "*-vim", "vim-*", etc. are all common).

**Comment by let-def** [comment]
With help from @pqwy, we did a NeoVim mode for TeXpresso.
It is still rough: not much tested, limited feature set, I don't know the Neovim conventions well yet, so I am probably breaking them etc.
However, it sufficient for testing!

**Comment by let-def** [comment]
The mode is usable, I am closing this issue, further discussions about vim will happen on the dedicated repository.
