### ISSUE TITLE
Unable to test TeXpresso

### ISSUE THREAD

**Issue by hei411** [let-def/texpresso#24]
I am reporting an issue as I am unable to perform the test `build/texpresso test/simple.tex`

After running, the program enters an infinite loop with the last few lines as follows:
```
success:1 size:35469
[dvi] loading cmmi8
success:1 size:1520
[dvi] loading cmmi8
success:0 size:9
bundle_serve_hooks_cat: error loading cmmi8.vf: not found
(flush)

optimized bounds: 0.000000,0.000000 - 700.000000,900.000061
```

I am running on Linux Mint 21.2 Cinnamon, with x86_64.
The model is Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

**Comment by let-def** [comment]
Hi, thanks for trying out.

I was able to run TeXpresso correctly on a freshly installed Linux Mint Cinnamon (21.3), however the build process required a lot of patches, so I wonder how you managed to build it on your system.
Namely, MuPDF and SDL2 are too old. I had to build a custom version of libmupdf (and customize `Makefile.config` to use the local version), and for SDL2, I had to disable hidpi checks and some event handling (as a quick workaround).

Understanding your build environment will help diagnosing problems.

**Comment by hei411** [comment]
I did not run into any problems building it; I just had to install various dependencies as I go, such as gumbo, graphite2 and openjpeg.

mupdf is of version 1.23.10 from https://mupdf.com/releases/index.html
SDL2 directly build from https://github.com/libsdl-org/SDL.git
pkg-config installed from package manager (version 0.29.2)
re2c from package manager (version 3.0)

Let me know if this helps. Happy to provide more info.

**Comment by let-def** [comment]
A backtrace of the looping process would help. You can take one using `gdb` and `bt` command, or by recording a `perf` profile. Tell me if you need more guidance on these tools.

My current hypothesis is a problem with your local build of SDL2, since the log you posted looks like a normal initialization, that stops before opening a window. Maybe you could try rebuilding with the packaged version of SDL2, let me prepare a patch...

**Comment by let-def** [comment]
The current `main` branch should build with Linux Mint versions of SDL2 :).

**Comment by hei411** [comment]
Hello, I attempted to reinstall everything with the current `main`  branch, i.e. `make all`
I encountered two errors during the installation:

```
cc1: fatal error: build/mupdf_test.c: No such file or directory
compilation terminated....
```

And then many lines later

```
cd tectonic &&  cargo build --release
error: could not find `Cargo.toml` in `/home/heili/Documents/build/texpresso/tectonic` or any parent directory
make[2]: *** [Makefile.tectonic:4: tectonic] Error 101
make[2]: Leaving directory '/home/heili/Documents/build/texpresso'
```

**Comment by let-def** [comment]
The second error suggest that git submodules were not properly setup.
After cloning the repository, you should run `git submodule update --init --recursive`

The first error is even more puzzling: mupdf_test.c is generated only to try to guess the appropriate libmupdf flags, and it is used literally one (shell) line after having been generated in `mupdf-config.sh`. My best guess is a race condition, maybe due to parallel build. Maybe try starting from a fresh clone.

**Comment by hei411** [comment]
The good news is that I was able to get texpresso to work now.
The (slightly) bad news is that after `make all` I still get the first error message. As you might have guessed, it happens in one of the first few lines, i.e.:
```
heili@heili-laptop:~/Documents/build/texpresso$ make all
make texpresso
make[1]: Entering directory '/home/heili/Documents/build/texpresso'
make -C src texpresso
make[2]: Entering directory '/home/heili/Documents/build/texpresso/src'
make -C .. config
make[3]: Entering directory '/home/heili/Documents/build/texpresso'
cc1: fatal error: build/mupdf_test.c: No such file or directory

```

However, I am able to get texpresso to work, so I am happy for this issue to be closed for now. Thank you.
